code --install-extension dbaeumer.vscode-eslint
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.path-intellisense
code --install-extension codingyu.laravel-goto-view
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dariofuzinato.vue-peek
code --install-extension daylerees.rainglow
code --install-extension dbaeumer.vscode-eslint
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-debug
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension GitHub.copilot
code --install-extension hwencc.html-tag-wrapper
code --install-extension kiteco.kite
code --install-extension mikestead.dotenv
code --install-extension octref.vetur
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel-extension-pack
code --install-extension onecentlin.laravel5-snippets
code --install-extension peaceshi.syntax-highlight
code --install-extension PKief.material-icon-theme
code --install-extension pranaygp.vscode-css-peek
code --install-extension reloadedextensions.reloaded-themes
code --install-extension ryannaddy.laravel-artisan
code --install-extension sdras.vue-vscode-snippets
code --install-extension SonarSource.sonarlint-vscode
code --install-extension stef-k.laravel-goto-controller
code --install-extension vscodevim.vim
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xaver.clang-format
code --install-extension ypresto.vscode-intelli-refactor
sudo apt-get install fonts-cascadia-code